# Branch Protection Rules for 241Runners Awareness
# This file defines protection rules for the main branch

name: "Main Branch Protection"
description: "Protects the main branch with comprehensive rules"

# Branch Protection Rules
branch_protection_rules:
  - pattern: "main"
    required_status_checks:
      strict: true
      contexts:
        - "ci/build"
        - "ci/test"
        - "ci/lint"
    
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      require_last_push_approval: true
    
    enforce_admins: true
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
    required_conversation_resolution: true
    
    # Require signed commits
    required_signatures: false
    
    # Require linear history
    required_linear_history: false
    
    # Lock branch
    lock_branch: false
    
    # Allow bypass for specific users/teams
    bypass_pull_request_allowances:
      users: []
      teams: []
    
    # Restrict pushes that create files
    allow_fork_syncing: true
    
    # Required deployments
    required_deployments:
      environments: []
    
    # Required workflows
    required_workflows: []

# Additional Security Settings
security_settings:
  # Enable security features
  enable_secret_scanning: true
  enable_secret_scanning_push_protection: true
  enable_dependency_graph: true
  enable_dependabot_alerts: true
  enable_dependabot_security_updates: true
  
  # Code scanning
  enable_code_scanning: false
  
  # Advanced security
  enable_advanced_security: false

# Repository Rules
repository_rules:
  # Require pull request reviews
  require_pull_request_reviews: true
  required_approving_review_count: 1
  dismiss_stale_reviews: true
  require_code_owner_reviews: false
  
  # Require status checks
  require_status_checks: true
  strict_status_checks: true
  
  # Require branches to be up to date
  require_branches_to_be_up_to_date: true
  
  # Require signed commits
  require_signed_commits: false
  
  # Require linear history
  require_linear_history: false
  
  # Allow force pushes
  allow_force_pushes: false
  
  # Allow deletions
  allow_deletions: false
  
  # Require conversation resolution
  require_conversation_resolution: true

# Code Owners (if you want to set up code ownership)
code_owners:
  # Uncomment and modify as needed
  # - path: "*.js"
  #   owners: ["@your-username"]
  # - path: "*.css"
  #   owners: ["@your-username"]
  # - path: "*.html"
  #   owners: ["@your-username"]
  # - path: "backend/*"
  #   owners: ["@your-username"]

# Workflow Permissions
workflow_permissions:
  # Allow GitHub Actions to create and approve pull requests
  actions: "read"
  checks: "write"
  contents: "read"
  deployments: "read"
  discussions: "read"
  id_token: "write"
  issues: "read"
  packages: "read"
  pages: "read"
  pull_requests: "read"
  repository_hooks: "read"
  repository_projects: "read"
  security_events: "read"
  statuses: "write"

# Environment Protection Rules
environments:
  production:
    protection_rules:
      - required_reviewers:
          users: []
          teams: []
        wait_timer: 0
        deployment_branch_policy:
          protected_branches: true
          custom_branch_policies: false
        environment_secrets:
          - name: "PRODUCTION_API_KEY"
            visibility: "selected"
        environment_variables:
          - name: "NODE_ENV"
            value: "production"
