-- Fix Runners table by adding missing columns
-- This script adds the missing columns that are causing 500 errors

PRINT 'Starting Runners table column fixes...'

-- Add missing columns to Runners table
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'EyeColor')
    ALTER TABLE Runners ADD EyeColor NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'Height')
    ALTER TABLE Runners ADD Height NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'Weight')
    ALTER TABLE Runners ADD Weight NVARCHAR(50) NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'LastPhotoUpdate')
    ALTER TABLE Runners ADD LastPhotoUpdate DATETIME2 NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'NextPhotoReminder')
    ALTER TABLE Runners ADD NextPhotoReminder DATETIME2 NULL;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'PhotoUpdateReminderCount')
    ALTER TABLE Runners ADD PhotoUpdateReminderCount INT DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'PhotoUpdateReminderSent')
    ALTER TABLE Runners ADD PhotoUpdateReminderSent BIT DEFAULT 0;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Runners' AND COLUMN_NAME = 'Status')
    ALTER TABLE Runners ADD Status NVARCHAR(50) NULL;

PRINT 'Runners table column fixes completed successfully!'
