// Mock API Data for 241 Runners Awareness
// Houston Area Missing Persons Data - 64.4 mile radius coverage

const mockHoustonData = {
    individuals: [
        {
            id: 1001,
            fullName: "Sarah Johnson",
            dateOfBirth: "2005-03-15",
            gender: "Female",
            currentStatus: "Missing",
            dateAdded: "2025-01-15",
            latitude: 29.7604,
            longitude: -95.3698,
            address: "1234 Main St",
            city: "Houston",
            state: "TX",
            zipCode: "77002",
            description: "Last seen wearing blue jeans and white shirt near downtown Houston. Has special needs and may be disoriented.",
            contactInfo: "713-555-0101"
        },
        {
            id: 1002,
            fullName: "Michael Rodriguez",
            dateOfBirth: "1999-07-22",
            gender: "Male",
            currentStatus: "Urgent",
            dateAdded: "2025-01-20",
            latitude: 29.7599,
            longitude: -95.3698,
            address: "456 Memorial Dr",
            city: "Houston",
            state: "TX",
            zipCode: "77007",
            description: "Medical condition requires immediate attention. Last seen near Memorial Park.",
            contactInfo: "713-555-0202"
        },
        {
            id: 1003,
            fullName: "Emily Chen",
            dateOfBirth: "2002-11-08",
            gender: "Female",
            currentStatus: "Found",
            dateAdded: "2025-01-10",
            latitude: 29.7610,
            longitude: -95.3690,
            address: "789 Washington Ave",
            city: "Houston",
            state: "TX",
            zipCode: "77007",
            description: "Located safe at local shelter. Reunited with family.",
            contactInfo: "713-555-0303"
        },
        {
            id: 1004,
            fullName: "David Thompson",
            dateOfBirth: "1995-12-03",
            gender: "Male",
            currentStatus: "Safe",
            dateAdded: "2025-01-05",
            latitude: 29.7608,
            longitude: -95.3702,
            address: "321 Heights Blvd",
            city: "Houston",
            state: "TX",
            zipCode: "77008",
            description: "Returned home safely. Was staying with friends.",
            contactInfo: "713-555-0404"
        },
        {
            id: 1005,
            fullName: "Lisa Martinez",
            dateOfBirth: "2000-09-14",
            gender: "Female",
            currentStatus: "Missing",
            dateAdded: "2025-01-18",
            latitude: 29.7602,
            longitude: -95.3695,
            address: "654 Westheimer Rd",
            city: "Houston",
            state: "TX",
            zipCode: "77006",
            description: "Last seen at local shopping center. May be trying to get home.",
            contactInfo: "713-555-0505"
        },
        {
            id: 1006,
            fullName: "James Wilson",
            dateOfBirth: "1997-04-30",
            gender: "Male",
            currentStatus: "Urgent",
            dateAdded: "2025-01-22",
            latitude: 29.7606,
            longitude: -95.3700,
            address: "987 Medical Center Blvd",
            city: "Houston",
            state: "TX",
            zipCode: "77030",
            description: "Special needs individual, requires medication. Last seen near medical center.",
            contactInfo: "713-555-0606"
        },
        {
            id: 1007,
            fullName: "Maria Garcia",
            dateOfBirth: "1993-01-25",
            gender: "Female",
            currentStatus: "Missing",
            dateAdded: "2025-01-12",
            latitude: 29.7600,
            longitude: -95.3692,
            address: "147 Buffalo Bayou Dr",
            city: "Houston",
            state: "TX",
            zipCode: "77002",
            description: "Last seen walking near Buffalo Bayou Park. May be confused about location.",
            contactInfo: "713-555-0707"
        },
        {
            id: 1008,
            fullName: "Robert Davis",
            dateOfBirth: "1991-08-17",
            gender: "Male",
            currentStatus: "Found",
            dateAdded: "2025-01-08",
            latitude: 29.7605,
            longitude: -95.3699,
            address: "258 Hospital Dr",
            city: "Houston",
            state: "TX",
            zipCode: "77030",
            description: "Found at local hospital. Receiving medical care.",
            contactInfo: "713-555-0808"
        },
        {
            id: 1009,
            fullName: "Jennifer Lee",
            dateOfBirth: "1998-06-11",
            gender: "Female",
            currentStatus: "Missing",
            dateAdded: "2025-01-25",
            latitude: 29.7603,
            longitude: -95.3696,
            address: "369 Zoo Blvd",
            city: "Houston",
            state: "TX",
            zipCode: "77030",
            description: "Last seen at Houston Zoo. May be trying to find transportation home.",
            contactInfo: "713-555-0909"
        },
        {
            id: 1010,
            fullName: "Thomas Brown",
            dateOfBirth: "1996-02-28",
            gender: "Male",
            currentStatus: "Urgent",
            dateAdded: "2025-01-23",
            latitude: 29.7607,
            longitude: -95.3701,
            address: "741 Galleria Dr",
            city: "Houston",
            state: "TX",
            zipCode: "77056",
            description: "Autism spectrum disorder. May be overwhelmed by crowds. Last seen near Galleria.",
            contactInfo: "713-555-1010"
        },
        {
            id: 1011,
            fullName: "Amanda White",
            dateOfBirth: "2001-10-05",
            gender: "Female",
            currentStatus: "Safe",
            dateAdded: "2025-01-14",
            latitude: 29.7601,
            longitude: -95.3693,
            address: "852 Friends St",
            city: "Houston",
            state: "TX",
            zipCode: "77006",
            description: "Returned home safely. Was visiting friends and lost track of time.",
            contactInfo: "713-555-1111"
        },
        {
            id: 1012,
            fullName: "Christopher Taylor",
            dateOfBirth: "1994-05-19",
            gender: "Male",
            currentStatus: "Missing",
            dateAdded: "2025-01-26",
            latitude: 29.7609,
            longitude: -95.3697,
            address: "963 Rice Blvd",
            city: "Houston",
            state: "TX",
            zipCode: "77005",
            description: "Last seen near Rice University campus. May be seeking help or shelter.",
            contactInfo: "713-555-1212"
        },
        {
            id: 1013,
            fullName: "Jessica Anderson",
            dateOfBirth: "1999-12-07",
            gender: "Female",
            currentStatus: "Missing",
            dateAdded: "2025-01-27",
            latitude: 29.7612,
            longitude: -95.3705,
            address: "159 Sugar Land Dr",
            city: "Sugar Land",
            state: "TX",
            zipCode: "77479",
            description: "Last seen at Sugar Land Town Square. May be trying to get home.",
            contactInfo: "281-555-1313"
        },
        {
            id: 1014,
            fullName: "Kevin Martinez",
            dateOfBirth: "1997-03-21",
            gender: "Male",
            currentStatus: "Urgent",
            dateAdded: "2025-01-28",
            latitude: 29.7615,
            longitude: -95.3708,
            address: "753 Katy Freeway",
            city: "Katy",
            state: "TX",
            zipCode: "77494",
            description: "Special needs individual. Last seen near Katy Mills Mall.",
            contactInfo: "281-555-1414"
        },
        {
            id: 1015,
            fullName: "Rachel Green",
            dateOfBirth: "2000-08-13",
            gender: "Female",
            currentStatus: "Missing",
            dateAdded: "2025-01-29",
            latitude: 29.7618,
            longitude: -95.3710,
            address: "456 Spring Cypress Rd",
            city: "Spring",
            state: "TX",
            zipCode: "77388",
            description: "Last seen at Spring Creek Greenway. May be hiking or walking.",
            contactInfo: "281-555-1515"
        }
    ]
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = mockHoustonData;
}

// Make available globally for browser usage
if (typeof window !== 'undefined') {
    window.mockHoustonData = mockHoustonData;
}
