[build]
  base = "."
  command = ""
  publish = "."

# The base directory is specified in the package.json directory.
# All requests will be handled by the React app.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# The build command and redirects for the separate React app have been removed
# because the main site is now self-contained with its own login/signup pages. 