name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Frontend (HTML/CSS/JS)
        - Backend API
        - Authentication/Authorization
        - Real-time Features
        - Database
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down, data loss)
        - High (Major feature broken)
        - Medium (Minor feature broken)
        - Low (Cosmetic issue)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here...

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: e.g., Chrome 120.0.6099.109
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
        - Other
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 14.0, iOS 17.0
    validations:
      required: true

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs
      description: If applicable, paste any relevant console logs or error messages.
      placeholder: |
        ```
        Error: [paste error message here]
        ```
      render: shell

  - type: textarea
    id: network-logs
    attributes:
      label: Network Logs
      description: If applicable, paste any relevant network request/response logs.
      placeholder: |
        ```
        [paste network logs here]
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I have tested this on the latest version
          required: true
        - label: I have included relevant console/network logs
          required: false