-- 241 Runners Awareness: PostgreSQL schema mirroring Azure SQL / EF Core model
-- Apply via: supabase db push (staging) or supabase migration up
-- Preserves INTEGER PKs for zero-disruption API auth (ADR-001 Phase A)

CREATE TABLE IF NOT EXISTS "Users" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Email" VARCHAR(255) NOT NULL,
    "PasswordHash" VARCHAR(255),
    "AuthProvider" VARCHAR(50),
    "ProviderUserId" VARCHAR(255),
    "ProviderAccessToken" VARCHAR(500),
    "ProviderRefreshToken" VARCHAR(500),
    "ProviderTokenExpires" TIMESTAMPTZ,
    "FirstName" VARCHAR(100) NOT NULL,
    "LastName" VARCHAR(100) NOT NULL,
    "Role" VARCHAR(50) NOT NULL DEFAULT 'user',
    "AdditionalRoles" VARCHAR(200),
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "LastLoginAt" TIMESTAMPTZ,
    "UpdatedAt" TIMESTAMPTZ,
    "PhoneNumber" VARCHAR(20),
    "Address" VARCHAR(500),
    "City" VARCHAR(100),
    "State" VARCHAR(50),
    "ZipCode" VARCHAR(20),
    "Organization" VARCHAR(200),
    "Title" VARCHAR(100),
    "Credentials" VARCHAR(200),
    "Specialization" VARCHAR(200),
    "YearsOfExperience" VARCHAR(50),
    "ProfileImageUrl" VARCHAR(500),
    "AdditionalImageUrls" VARCHAR(1000),
    "DocumentUrls" VARCHAR(1000),
    "EmergencyContactName" VARCHAR(100),
    "EmergencyContactPhone" VARCHAR(20),
    "EmergencyContactRelationship" VARCHAR(100),
    "Notes" VARCHAR(2000),
    "IsEmailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsPhoneVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "EmailVerifiedAt" TIMESTAMPTZ,
    "PhoneVerifiedAt" TIMESTAMPTZ,
    "EmailVerificationToken" VARCHAR(255),
    "PasswordResetToken" VARCHAR(255),
    "PasswordResetTokenExpires" TIMESTAMPTZ,
    "ResetToken" VARCHAR(255),
    "ResetTokenExpires" TIMESTAMPTZ,
    "FailedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
    "LockedUntil" TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_EmailVerificationToken"
    ON "Users" ("EmailVerificationToken") WHERE "EmailVerificationToken" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_PasswordResetToken"
    ON "Users" ("PasswordResetToken") WHERE "PasswordResetToken" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "Runners" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "CreatedByUserId" INTEGER,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" TIMESTAMPTZ,
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Missing',
    "Name" VARCHAR(200) NOT NULL,
    "FirstName" VARCHAR(100),
    "LastName" VARCHAR(100),
    "Height" VARCHAR(10),
    "Weight" VARCHAR(10),
    "EyeColor" VARCHAR(20),
    "DateOfBirth" TIMESTAMPTZ NOT NULL,
    "Gender" VARCHAR(20) NOT NULL,
    "PhysicalDescription" VARCHAR(500),
    "MedicalConditions" VARCHAR(1000),
    "Medications" VARCHAR(1000),
    "Allergies" VARCHAR(1000),
    "EmergencyInstructions" VARCHAR(500),
    "PreferredRunningLocations" VARCHAR(200),
    "TypicalRunningTimes" VARCHAR(200),
    "ExperienceLevel" VARCHAR(100),
    "SpecialNeeds" VARCHAR(500),
    "AdditionalNotes" VARCHAR(1000),
    "LastKnownLocation" VARCHAR(50),
    "LastLocationUpdate" TIMESTAMPTZ,
    "PreferredContactMethod" VARCHAR(50),
    "ProfileImageUrl" VARCHAR(500),
    "AdditionalImageUrls" VARCHAR(1000),
    "IsProfileComplete" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "VerifiedAt" TIMESTAMPTZ,
    "VerifiedBy" VARCHAR(255),
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "ShowOnMap" BOOLEAN NOT NULL DEFAULT FALSE,
    "MapLatitude" NUMERIC(18,6),
    "MapLongitude" NUMERIC(18,6),
    "LastPhotoUpdate" TIMESTAMPTZ,
    "NextPhotoReminder" TIMESTAMPTZ,
    "PhotoUpdateReminderSent" BOOLEAN NOT NULL DEFAULT FALSE,
    "PhotoUpdateReminderCount" INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "IX_Runners_UserId" ON "Runners" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Runners_Status" ON "Runners" ("Status");

CREATE TABLE IF NOT EXISTS "Cases" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RunnerId" INTEGER NOT NULL REFERENCES "Runners"("Id") ON DELETE CASCADE,
    "ReportedByUserId" INTEGER NOT NULL REFERENCES "Users"("Id") ON DELETE RESTRICT,
    "CreatedByUserId" INTEGER,
    "Title" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(2000) NOT NULL,
    "LastSeenDate" TIMESTAMPTZ NOT NULL,
    "LastSeenTime" VARCHAR(100),
    "LastSeenLocation" VARCHAR(500) NOT NULL,
    "LastSeenLatitude" NUMERIC(18,6),
    "LastSeenLongitude" NUMERIC(18,6),
    "LastSeenAt" TIMESTAMPTZ,
    "LastSeenCircumstances" VARCHAR(1000),
    "ClothingDescription" VARCHAR(200),
    "PhysicalCondition" VARCHAR(200),
    "MentalState" VARCHAR(200),
    "AdditionalInformation" VARCHAR(1000),
    "Status" VARCHAR(50) NOT NULL,
    "Priority" VARCHAR(20) NOT NULL,
    "IsPublic" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsApproved" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" TIMESTAMPTZ,
    "ResolvedAt" TIMESTAMPTZ,
    "ResolutionNotes" VARCHAR(1000),
    "ResolvedBy" VARCHAR(200),
    "ContactPersonName" VARCHAR(100),
    "ContactPersonPhone" VARCHAR(20),
    "ContactPersonEmail" VARCHAR(255),
    "CaseImageUrls" VARCHAR(1000),
    "DocumentUrls" VARCHAR(1000),
    "Location" VARCHAR(500),
    "EmergencyContactName" VARCHAR(100),
    "EmergencyContactPhone" VARCHAR(20),
    "EmergencyContactRelationship" VARCHAR(100),
    "VerifiedAt" TIMESTAMPTZ,
    "VerifiedBy" VARCHAR(255),
    "ApprovedAt" TIMESTAMPTZ,
    "ApprovedBy" VARCHAR(255),
    "ViewCount" INTEGER NOT NULL DEFAULT 0,
    "ShareCount" INTEGER NOT NULL DEFAULT 0,
    "TipCount" INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS "IX_Cases_RunnerId" ON "Cases" ("RunnerId");
CREATE INDEX IF NOT EXISTS "IX_Cases_ReportedByUserId" ON "Cases" ("ReportedByUserId");

CREATE TABLE IF NOT EXISTS "Devices" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Platform" VARCHAR(10) NOT NULL,
    "FcmToken" VARCHAR(500) NOT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "LastSeenAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" TIMESTAMPTZ,
    "AppVersion" VARCHAR(20),
    "TopicsJson" VARCHAR(2000),
    "DeviceModel" VARCHAR(100),
    "OsVersion" VARCHAR(50),
    "AppBuildNumber" VARCHAR(100),
    UNIQUE ("UserId", "Platform")
);

CREATE TABLE IF NOT EXISTS "TopicSubscriptions" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Topic" VARCHAR(100) NOT NULL,
    "IsSubscribed" BOOLEAN NOT NULL DEFAULT TRUE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" TIMESTAMPTZ,
    "SubscriptionReason" VARCHAR(200),
    "NotificationCount" INTEGER NOT NULL DEFAULT 0,
    "LastNotificationSent" TIMESTAMPTZ,
    UNIQUE ("UserId", "Topic")
);

CREATE TABLE IF NOT EXISTS "Notifications" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "Title" VARCHAR(200) NOT NULL,
    "Body" VARCHAR(1000) NOT NULL,
    "Type" VARCHAR(50) NOT NULL,
    "Topic" VARCHAR(100),
    "DataJson" VARCHAR(2000),
    "IsSent" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsDelivered" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsOpened" BOOLEAN NOT NULL DEFAULT FALSE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "SentAt" TIMESTAMPTZ,
    "DeliveredAt" TIMESTAMPTZ,
    "OpenedAt" TIMESTAMPTZ,
    "ExpiresAt" TIMESTAMPTZ,
    "Priority" VARCHAR(100) NOT NULL DEFAULT 'normal',
    "ErrorMessage" VARCHAR(500),
    "RetryCount" INTEGER NOT NULL DEFAULT 0,
    "RelatedCaseId" INTEGER,
    "RelatedUserId" INTEGER
);

CREATE INDEX IF NOT EXISTS "IX_Notifications_UserId" ON "Notifications" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Notifications_Type" ON "Notifications" ("Type");
CREATE INDEX IF NOT EXISTS "IX_Notifications_Topic" ON "Notifications" ("Topic");
CREATE INDEX IF NOT EXISTS "IX_Notifications_CreatedAt" ON "Notifications" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_Notifications_IsSent" ON "Notifications" ("IsSent");

CREATE TABLE IF NOT EXISTS "DataDeletionRequests" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "DataTypes" VARCHAR(500) NOT NULL,
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Pending',
    "RequestedAt" TIMESTAMPTZ NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" TIMESTAMPTZ NOT NULL,
    "ProcessedAt" TIMESTAMPTZ,
    "Reason" VARCHAR(1000),
    "ProcessingNotes" VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS "IX_DataDeletionRequests_UserId" ON "DataDeletionRequests" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_DataDeletionRequests_Status" ON "DataDeletionRequests" ("Status");
CREATE INDEX IF NOT EXISTS "IX_DataDeletionRequests_RequestedAt" ON "DataDeletionRequests" ("RequestedAt");

CREATE TABLE IF NOT EXISTS "AccountDeletionRequests" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL REFERENCES "Users"("Id") ON DELETE CASCADE,
    "UserEmail" VARCHAR(254) NOT NULL,
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Pending',
    "RequestedAt" TIMESTAMPTZ NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
    "UpdatedAt" TIMESTAMPTZ NOT NULL,
    "ProcessedAt" TIMESTAMPTZ,
    "Reason" VARCHAR(1000),
    "ProcessingNotes" VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS "IX_AccountDeletionRequests_UserId" ON "AccountDeletionRequests" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AccountDeletionRequests_Status" ON "AccountDeletionRequests" ("Status");
CREATE INDEX IF NOT EXISTS "IX_AccountDeletionRequests_RequestedAt" ON "AccountDeletionRequests" ("RequestedAt");

COMMENT ON TABLE "Users" IS 'Legacy application users; auth remains API JWT until optional Supabase Auth cutover.';
