name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths:
      - '241RunnersAwarenessAPI/**'
  pull_request:
    branches: [ main ]
    paths:
      - '241RunnersAwarenessAPI/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 241runners-api
  AZURE_WEBAPP_PACKAGE_PATH: './241RunnersAwarenessAPI'
  DOTNET_VERSION: '8.0.x'

jobs:  build-and-deploy:
on:
  push:
    branches: [ main ]
    paths:
      - '241RunnersAwarenessAPI/**'
  pull_request:
    branches: [ main ]
    paths:
      - '241RunnersAwarenessAPI/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 241runners-api
  AZURE_WEBAPP_PACKAGE_PATH: './241RunnersAwarenessAPI'
  DOTNET_VERSION: '8.0.x'

jobs: