name: Deploy Backend to Azure

on:
  push:
    branches: [ main ]
    paths:
      - '241RunnersAwarenessAPI/**'
  pull_request:
    branches: [ main ]
    paths:
      - '241RunnersAwarenessAPI/**'

env:
  AZURE_WEBAPP_NAME: 241runners-api
  AZURE_WEBAPP_PACKAGE_PATH: './241RunnersAwarenessAPI'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: |
        cd 241RunnersAwarenessAPI
        dotnet restore
        
    - name: Build with dotnet
      run: |
        cd 241RunnersAwarenessAPI
        dotnet build --configuration Release --no-restore
        
    - name: Publish with dotnet
      run: |
        cd 241RunnersAwarenessAPI
        dotnet publish -c Release -o ./publish
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./241RunnersAwarenessAPI/publish
        
    - name: Wait for deployment
      run: |
        echo "Waiting for Azure deployment to complete..."
        sleep 60
        
    - name: Test health endpoint
      run: |
        echo "Testing API health endpoint..."
        for i in {1..5}; do
          if curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/Auth/health; then
            echo "✅ Health endpoint working"
            break
          else
            echo "Attempt $i failed, retrying in 10 seconds..."
            sleep 10
          fi
        done
        
    - name: Test database cleanup endpoint
      run: |
        echo "Testing database cleanup endpoint..."
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/DatabaseCleanup/stats || echo "Database cleanup endpoint not accessible"
        echo "✅ API deployment successful"
