name: Branch Protection Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # Security and Code Quality Checks
  security-checks:
    name: Security & Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          if [ -f "package.json" ] && [ -f "package-lock.json" ]; then
            npm ci
          elif [ -f "package.json" ]; then
            echo "No package-lock.json found, skipping dependency installation"
          else
            echo "No package.json found, skipping dependency installation"
          fi
          
      - name: Run security audit
        run: |
          if [ -f "package.json" ] && [ -f "package-lock.json" ]; then
            npm audit --audit-level=moderate || echo "Security audit completed with warnings"
          else
            echo "No package-lock.json found, skipping security audit"
          fi
          
      - name: Check for secrets in code
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified --fail
        continue-on-error: true
          
      - name: Validate HTML
        run: |
          echo "Validating HTML files..."
          find . -name "*.html" -type f -not -path "./.git/*" -not -path "./241RunnersAwarenessAPI/*" | head -10 | while read file; do
            echo "Validating $file"
            if grep -q "<!DOCTYPE html>" "$file"; then
              echo "✅ $file has valid DOCTYPE"
            else
              echo "⚠️ $file missing DOCTYPE"
            fi
          done
          
      - name: Check for broken internal links
        run: |
          echo "Checking for common link issues..."
          # Check if main navigation files exist
          if [ -f "index.html" ]; then
            echo "✅ index.html exists"
          else
            echo "❌ index.html missing"
            exit 1
          fi
          
          if [ -f "admin/login.html" ]; then
            echo "✅ admin/login.html exists"
          else
            echo "❌ admin/login.html missing"
            exit 1
          fi
          
          if [ -f "admin/admindash.html" ]; then
            echo "✅ admin/admindash.html exists"
          else
            echo "❌ admin/admindash.html missing"
            exit 1
          fi
          
      - name: Validate API configuration
        run: |
          echo "Validating API configuration..."
          if [ -f "config.json" ]; then
            echo "✅ config.json exists"
            if grep -q "241runners-api.azurewebsites.net" config.json; then
              echo "✅ API URL configured correctly"
            else
              echo "⚠️ API URL may not be configured correctly"
            fi
          else
            echo "❌ config.json missing"
            exit 1
          fi
          
      - name: Check file structure
        run: |
          echo "Checking essential file structure..."
          required_files=(
            "index.html"
            "admin/login.html"
            "admin/admindash.html"
            "config.json"
            "assets/js/config.js"
          )
          
          for file in "${required_files[@]}"; do
            if [ -f "$file" ]; then
              echo "✅ $file exists"
            else
              echo "❌ $file missing"
              exit 1
            fi
          done
          
      - name: Validate admin dashboard
        run: |
          echo "Validating admin dashboard..."
          if [ -f "admin/admindash.html" ]; then
            if grep -q "241runners-api.azurewebsites.net" admin/admindash.html; then
              echo "✅ Admin dashboard API URL configured correctly"
            else
              echo "⚠️ Admin dashboard API URL may not be configured correctly"
            fi
          fi
          
      - name: Check for sensitive data
        run: |
          echo "Checking for sensitive data..."
          # Check for hardcoded passwords or keys
          if grep -r -i "password.*=" . --include="*.html" --include="*.js" --include="*.json" | grep -v "placeholder" | grep -v "example"; then
            echo "⚠️ Potential hardcoded passwords found"
          else
            echo "✅ No hardcoded passwords found"
          fi
          
      - name: Validate CORS configuration
        run: |
          echo "Validating CORS configuration..."
          if [ -f "241RunnersAwarenessAPI/appsettings.Production.json" ]; then
            if grep -q "241runnersawareness.org" 241RunnersAwarenessAPI/appsettings.Production.json; then
              echo "✅ CORS configured for production domain"
            else
              echo "⚠️ CORS may not be configured for production domain"
            fi
          fi
          
      - name: Check database cleanup functionality
        run: |
          echo "Checking database cleanup functionality..."
          if [ -f "241RunnersAwarenessAPI/Services/DatabaseCleanupService.cs" ]; then
            echo "✅ DatabaseCleanupService exists"
          else
            echo "❌ DatabaseCleanupService missing"
            exit 1
          fi
          
          if [ -f "241RunnersAwarenessAPI/Controllers/DatabaseCleanupController.cs" ]; then
            echo "✅ DatabaseCleanupController exists"
          else
            echo "❌ DatabaseCleanupController missing"
            exit 1
          fi
          
      - name: Final validation
        run: |
          echo "🎉 All branch protection checks passed!"
          echo "✅ Security checks completed"
          echo "✅ HTML validation completed"
          echo "✅ File structure validated"
          echo "✅ API configuration validated"
          echo "✅ Database cleanup functionality verified"
