name: Deploy to GitHub Pages (DISABLED - Using pages.yml instead)

on:
  # DISABLED - This workflow conflicts with pages.yml
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch: # Only allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build (if needed)
      run: echo "Static site - no build step required"
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          241RunnersAPI/
          node_modules/
          .git/
          .github/
          *.zip
          publish/
          bin/
          obj/
