name: Frontend Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - '*.html'
      - '*.js'
      - '*.css'
      - '*.json'
      - 'admin/**'
      - 'js/**'
      - 'assets/**'
      - 'scripts/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '*.html'
      - '*.js'
      - '*.css'
      - '*.json'
      - 'admin/**'
      - 'js/**'
      - 'assets/**'
      - 'scripts/**'
      - '.github/workflows/frontend.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint JavaScript files
        run: |
          # Install ESLint if not present
          if [ ! -f "package.json" ] || ! grep -q "eslint" package.json; then
            npm install --save-dev eslint
          fi
          
          # Lint JS files
          find . -name "*.js" -not -path "./node_modules/*" -not -path "./.git/*" | xargs npx eslint --no-eslintrc --env browser,es6 --parser-options ecmaVersion:2020 --rule "no-console: warn" || true
          
      - name: Validate HTML
        run: |
          # Install html-validate if not present
          if [ ! -f "package.json" ] || ! grep -q "html-validate" package.json; then
            npm install --save-dev html-validate
          fi
          
          # Validate HTML files
          find . -name "*.html" -not -path "./node_modules/*" -not -path "./.git/*" | xargs npx html-validate --config .htmlvalidate.json || true
          
      - name: Check for security issues
        run: |
          # Check for common security issues
          echo "Checking for hardcoded secrets..."
          if grep -r "password.*=" . --include="*.js" --include="*.html" --include="*.json" | grep -v "example" | grep -v "test"; then
            echo "⚠️ Potential hardcoded passwords found"
          fi
          
          if grep -r "api.*key" . --include="*.js" --include="*.html" --include="*.json" | grep -v "example" | grep -v "test"; then
            echo "⚠️ Potential hardcoded API keys found"
          fi

  build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for git info
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build assets
        run: |
          # Make build script executable
          chmod +x scripts/build.js
          
          # Run build script
          node scripts/build.js
          
      - name: Verify build artifacts
        run: |
          echo "Checking build artifacts..."
          ls -la version.json
          ls -la asset-manifest.json
          
          # Verify version.json structure
          node -e "
            const version = JSON.parse(require('fs').readFileSync('version.json', 'utf8'));
            console.log('Version:', version.version);
            console.log('Build:', version.build);
            console.log('Commit:', version.commit);
            console.log('Assets:', version.assets);
          "
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          exclude_assets: |
            .git
            .github
            node_modules
            *.md
            .gitignore
            .env*
            scripts/
            
      - name: Update deployment status
        run: |
          echo "✅ Frontend deployed successfully"
          echo "🌐 Site: https://241runnersawareness.org"
          echo "📊 Version: $(cat version.json | jq -r '.version')"
          echo "🔗 Commit: $(cat version.json | jq -r '.commit')"

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'