name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-static-site:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Prepare static site files
      run: |
        # Create a temporary directory for static files
        mkdir -p static-site
        
        # Copy all static files and directories
        cp -r *.html *.css *.js *.jpg *.jpeg *.png *.pdf static-site/ 2>/dev/null || true
        cp -r admin/ assets/ js/ partials/ docs/ static-site/ 2>/dev/null || true
        cp CNAME _headers config.json static-site/ 2>/dev/null || true
        
        # List what we have
        echo "Static site files prepared:"
        ls -la static-site/
        
    - name: Upload static site files
      uses: actions/upload-pages-artifact@v3
      with:
        path: static-site
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 